// Minecraft Dungeons Master Item Catalog, Enchantments, and Missions
import {
  DungeonsGearItem,
  DungeonsArtifact,
  EnchantmentDefinition,
  DungeonsMission,
} from './types';

// --- ENCHANTMENTS CATALOG ---
export const ENCHANTMENT_DEFINITIONS: Record<string, EnchantmentDefinition> = {
  // MELEE
  radiance: {
    id: 'radiance',
    name: 'Radiance',
    icon: '✨',
    category: 'melee',
    description: 'Has a 20% chance to spawn a circular area that heals you and allies.',
    tierEffects: ['Heals 25 HP', 'Heals 55 HP', 'Heals 100 HP'],
    tierCosts: [1, 2, 3],
  },
  critical_hit: {
    id: 'critical_hit',
    name: 'Critical Hit',
    icon: '💥',
    category: 'melee',
    description: 'Gives you a chance to inflict triple damage with regular strikes.',
    tierEffects: ['10% chance for 3x damage', '15% chance for 3x damage', '20% chance for 3x damage'],
    tierCosts: [1, 2, 3],
  },
  sharpness: {
    id: 'sharpness',
    name: 'Sharpness',
    icon: '🗡️',
    category: 'melee',
    description: 'Increases all melee damage dealt to all enemies.',
    tierEffects: ['+15% melee damage', '+25% melee damage', '+40% melee damage'],
    tierCosts: [1, 2, 3],
  },
  leeching: {
    id: 'leeching',
    name: 'Leeching',
    icon: '🩸',
    category: 'melee',
    description: 'Defeating a mob heals a portion of your maximum health.',
    tierEffects: ['Heals 4% max HP', 'Heals 7% max HP', 'Heals 11% max HP'],
    tierCosts: [1, 2, 3],
  },
  fire_aspect: {
    id: 'fire_aspect',
    name: 'Fire Aspect',
    icon: '🔥',
    category: 'melee',
    description: 'Sets enemies ablaze, dealing continuous fire damage over 3 seconds.',
    tierEffects: ['Burn 15 dmg/sec', 'Burn 35 dmg/sec', 'Burn 65 dmg/sec'],
    tierCosts: [1, 2, 3],
  },
  swirling: {
    id: 'swirling',
    name: 'Swirling',
    icon: '🌪️',
    category: 'melee',
    description: 'The last attack in a combo performs a wide swirling slash.',
    tierEffects: ['Deals 20 damage', 'Deals 45 damage', 'Deals 80 damage'],
    tierCosts: [1, 2, 3],
  },

  // RANGED
  multi_shot: {
    id: 'multi_shot',
    name: 'Multi-Shot',
    icon: '🎯',
    category: 'ranged',
    description: 'Grants a chance to fire 5 arrows at once instead of one.',
    tierEffects: ['20% chance to fire 5 arrows', '30% chance to fire 5 arrows', '40% chance to fire 5 arrows'],
    tierCosts: [1, 2, 3],
  },
  power: {
    id: 'power',
    name: 'Power',
    icon: '⚡',
    category: 'ranged',
    description: 'Boosts all arrow projectile damage.',
    tierEffects: ['+15% arrow damage', '+25% arrow damage', '+40% arrow damage'],
    tierCosts: [1, 2, 3],
  },
  ricochet: {
    id: 'ricochet',
    name: 'Ricochet',
    icon: '🔄',
    category: 'ranged',
    description: 'Small chance for arrows to ricochet off mobs into secondary targets.',
    tierEffects: ['20% chance to ricochet', '40% chance to ricochet', '60% chance to ricochet'],
    tierCosts: [1, 2, 3],
  },
  infinity: {
    id: 'infinity',
    name: 'Infinity',
    icon: '♾️',
    category: 'ranged',
    description: 'Grants a high chance to immediately replenish the fired arrow.',
    tierEffects: ['24% arrow recovery', '36% arrow recovery', '48% arrow recovery'],
    tierCosts: [1, 2, 3],
  },

  // ARMOR
  protection: {
    id: 'protection',
    name: 'Protection',
    icon: '🛡️',
    category: 'armor',
    description: 'Reduces all incoming damage taken by a percentage.',
    tierEffects: ['+6% damage reduction', '+11% damage reduction', '+15% damage reduction'],
    tierCosts: [1, 2, 3],
  },
  thorns: {
    id: 'thorns',
    name: 'Thorns',
    icon: '🦔',
    category: 'armor',
    description: 'Reflects a percentage of incoming damage back to the attacker.',
    tierEffects: ['100% damage reflected', '150% damage reflected', '200% damage reflected'],
    tierCosts: [1, 2, 3],
  },
  swiftfooted: {
    id: 'swiftfooted',
    name: 'Swiftfooted',
    icon: '💨',
    category: 'armor',
    description: 'Rolling grants a significant burst of movement speed for 3 seconds.',
    tierEffects: ['+30% roll speed', '+40% roll speed', '+50% roll speed'],
    tierCosts: [1, 2, 3],
  },
  potion_barrier: {
    id: 'potion_barrier',
    name: 'Potion Barrier',
    icon: '🧪',
    category: 'armor',
    description: 'Drinking your health potion grants 90% damage reduction for a short duration.',
    tierEffects: ['Takes -90% damage for 5s', 'Takes -90% damage for 7s', 'Takes -90% damage for 9s'],
    tierCosts: [1, 2, 3],
  },
};

// --- ARTIFACTS CATALOG ---
export const ALL_ARTIFACTS: DungeonsArtifact[] = [
  {
    id: 'death_cap_mushroom',
    name: 'Death Cap Mushroom',
    category: 'artifact',
    rarity: 'rare',
    power: 28,
    icon: '🍄',
    color: '#ef4444',
    description: 'Eat to enter a frenzied state, dramatically increasing your attack speed and movement speed.',
    effect: 'death_cap_mushroom',
    cooldownSec: 15,
    durationSec: 9,
    salvageEmeralds: 75,
  },
  {
    id: 'fireworks_arrow',
    name: 'Fireworks Arrow',
    category: 'artifact',
    rarity: 'rare',
    power: 32,
    icon: '🎆',
    color: '#f97316',
    description: 'Places a TNT-loaded rocket into your quiver. Your next ranged shot detonates on impact in a massive colorful explosion!',
    effect: 'fireworks_arrow',
    cooldownSec: 18,
    salvageEmeralds: 85,
  },
  {
    id: 'corrupted_beacon',
    name: 'Corrupted Beacon',
    category: 'artifact',
    rarity: 'unique',
    power: 38,
    icon: '🔮',
    color: '#c084fc',
    description: 'Harnesses collected souls to project an intense high-damage beam of arcane energy, obliterating all foes.',
    effect: 'corrupted_beacon',
    cooldownSec: 2,
    soulCost: 10,
    durationSec: 3,
    salvageEmeralds: 140,
  },
  {
    id: 'boots_of_swiftness',
    name: 'Boots of Swiftness',
    category: 'artifact',
    rarity: 'common',
    power: 20,
    icon: '👢',
    color: '#0ea5e9',
    description: 'Lightweight enchanted boots that grant a substantial burst of sprinting speed to evade ambushes.',
    effect: 'boots_of_swiftness',
    cooldownSec: 10,
    durationSec: 4.5,
    salvageEmeralds: 45,
  },
  {
    id: 'iron_hide_amulet',
    name: 'Iron Hide Amulet',
    category: 'artifact',
    rarity: 'rare',
    power: 30,
    icon: '📿',
    color: '#94a3b8',
    description: 'An ancient protective talisman that reinforces your skin, reducing incoming damage by 50% for a duration.',
    effect: 'iron_hide_amulet',
    cooldownSec: 20,
    durationSec: 10,
    salvageEmeralds: 90,
  },
  {
    id: 'harvester',
    name: 'Harvester',
    category: 'artifact',
    rarity: 'rare',
    power: 34,
    icon: '💀',
    color: '#a855f7',
    description: 'Consumes souls to unleash an explosive radial shockwave around you, knocking back and annihilating surrounding mobs.',
    effect: 'harvester',
    cooldownSec: 5,
    soulCost: 15,
    salvageEmeralds: 95,
  },
  {
    id: 'wind_horn',
    name: 'Wind Horn',
    category: 'artifact',
    rarity: 'common',
    power: 22,
    icon: '📯',
    color: '#38bdf8',
    description: 'Blow the enchanted horn to push enemies away with a gale force gust and temporarily slow their movement.',
    effect: 'wind_horn',
    cooldownSec: 12,
    salvageEmeralds: 50,
  },
  {
    id: 'tasty_bone',
    name: 'Tasty Bone',
    category: 'artifact',
    rarity: 'rare',
    power: 26,
    icon: '🦴',
    color: '#fde047',
    description: 'Summons a fearless and loyal Wolf companion that actively attacks hostile mobs alongside you.',
    effect: 'tasty_bone',
    cooldownSec: 30,
    salvageEmeralds: 80,
  },
];

// --- MELEE WEAPONS CATALOG ---
export const ALL_MELEE_WEAPONS: DungeonsGearItem[] = [
  {
    id: 'starter_wooden_sword',
    name: 'Carved Wooden Sword',
    category: 'melee',
    subType: 'sword',
    rarity: 'common',
    power: 1,
    icon: '🗡️',
    color: '#854d0e',
    damage: 12,
    attackSpeed: 1.0,
    range: 2.2,
    description: 'A novice blade hand-carved from forest timber. Your journey begins with this humble weapon.',
    enchantmentSlots: [
      { id: 'sharpness', tier: 0 },
    ],
    salvageEmeralds: 5,
  },
  {
    id: 'diamond_sword',
    name: 'Diamond Sword',
    category: 'melee',
    subType: 'sword',
    rarity: 'unique',
    power: 34,
    icon: '💎',
    color: '#38bdf8',
    damage: 48,
    attackSpeed: 1.15,
    range: 2.8,
    description: 'The crowning glory of Minecraft weaponry, forged from pure crystallized diamond.',
    uniquePerk: 'Extra damage and built-in +15% Critical Chance',
    enchantmentSlots: [
      { id: 'radiance', tier: 1 },
      { id: 'sharpness', tier: 1 },
      { id: 'critical_hit', tier: 0 },
    ],
    salvageEmeralds: 150,
  },
  {
    id: 'fighters_bindings',
    name: "Fighter's Bindings",
    category: 'melee',
    subType: 'gauntlets',
    rarity: 'unique',
    power: 38,
    icon: '🥊',
    color: '#f59e0b',
    damage: 28,
    attackSpeed: 2.2, // Ultra rapid flurry strikes!
    range: 2.2,
    description: 'Turbo-speed gauntlets that unleash an unstoppable flurry of high-speed jabs.',
    uniquePerk: 'Turbo attack speed with rapid finishing combo',
    enchantmentSlots: [
      { id: 'radiance', tier: 2 },
      { id: 'swirling', tier: 1 },
      { id: 'critical_hit', tier: 1 },
    ],
    salvageEmeralds: 200,
  },
  {
    id: 'cursed_axe',
    name: 'Cursed Axe',
    category: 'melee',
    subType: 'axe',
    rarity: 'unique',
    power: 36,
    icon: '🪓',
    color: '#8b5cf6',
    damage: 62,
    attackSpeed: 0.9,
    range: 3.4,
    description: 'A double-bladed battleaxe that spins in a devastating 360-degree sweep.',
    uniquePerk: 'Defeated mobs explode, damaging nearby enemies',
    enchantmentSlots: [
      { id: 'leeching', tier: 1 },
      { id: 'sharpness', tier: 1 },
      { id: 'fire_aspect', tier: 0 },
    ],
    salvageEmeralds: 180,
  },
  {
    id: 'suns_grace',
    name: "Sun's Grace",
    category: 'melee',
    subType: 'mace',
    rarity: 'unique',
    power: 32,
    icon: '☀️',
    color: '#fde047',
    damage: 44,
    attackSpeed: 1.0,
    range: 2.6,
    description: 'A holy mace blessed by the radiant sun that restores health to the wielder upon striking.',
    uniquePerk: 'Radiance built-in, striking heals the hero',
    enchantmentSlots: [
      { id: 'radiance', tier: 1 },
      { id: 'critical_hit', tier: 0 },
      { id: 'sharpness', tier: 0 },
    ],
    salvageEmeralds: 140,
  },
  {
    id: 'broadsword',
    name: 'Iron Broadsword',
    category: 'melee',
    subType: 'sword',
    rarity: 'common',
    power: 16,
    icon: '⚔️',
    color: '#94a3b8',
    damage: 26,
    attackSpeed: 1.0,
    range: 2.5,
    description: 'A reliable iron blade wielded by Overworld village guards.',
    enchantmentSlots: [
      { id: 'sharpness', tier: 0 },
      { id: 'fire_aspect', tier: 0 },
    ],
    salvageEmeralds: 35,
  },
  {
    id: 'claymore',
    name: 'Great Claymore',
    category: 'melee',
    subType: 'claymore',
    rarity: 'rare',
    power: 24,
    icon: '🗡️',
    color: '#60a5fa',
    damage: 54,
    attackSpeed: 0.75,
    range: 3.6,
    description: 'A massive two-handed sword with huge cleave reach and heavy knockback.',
    enchantmentSlots: [
      { id: 'sharpness', tier: 0 },
      { id: 'swirling', tier: 0 },
      { id: 'critical_hit', tier: 0 },
    ],
    salvageEmeralds: 70,
  },
];

// --- RANGED WEAPONS CATALOG ---
export const ALL_RANGED_WEAPONS: DungeonsGearItem[] = [
  {
    id: 'starter_shortbow',
    name: 'Crude Shortbow',
    category: 'ranged',
    subType: 'shortbow',
    rarity: 'common',
    power: 1,
    icon: '🏹',
    color: '#a16207',
    damage: 14,
    range: 16,
    attackSpeed: 1.0,
    arrowCost: 1,
    description: 'A simple bent wooden branch strung with twine. Basic but reliable distance defense.',
    enchantmentSlots: [
      { id: 'power', tier: 0 },
    ],
    salvageEmeralds: 5,
  },
  {
    id: 'harp_crossbow',
    name: 'Harp Crossbow',
    category: 'ranged',
    subType: 'scatter_crossbow',
    rarity: 'unique',
    power: 36,
    icon: '🎻',
    color: '#f59e0b',
    damage: 32, // per bolt!
    range: 20,
    attackSpeed: 1.1,
    arrowCost: 1,
    description: 'An exquisitely strung crossbow that unleashes 5 bolts in a wide fanning spread!',
    uniquePerk: 'Shoots 5 projectiles per trigger pull',
    enchantmentSlots: [
      { id: 'multi_shot', tier: 1 },
      { id: 'ricochet', tier: 1 },
      { id: 'infinity', tier: 0 },
    ],
    salvageEmeralds: 180,
  },
  {
    id: 'firebolt_bow',
    name: 'Firebolt Bow',
    category: 'ranged',
    subType: 'power_bow',
    rarity: 'unique',
    power: 32,
    icon: '🏹',
    color: '#ef4444',
    damage: 58,
    range: 26,
    attackSpeed: 0.85,
    arrowCost: 1,
    description: 'Fires explosive incendiary arrows that detonate on impact.',
    uniquePerk: 'Explosive flaming arrow detonations',
    enchantmentSlots: [
      { id: 'power', tier: 1 },
      { id: 'infinity', tier: 0 },
      { id: 'ricochet', tier: 0 },
    ],
    salvageEmeralds: 160,
  },
  {
    id: 'red_snake',
    name: 'Red Snake',
    category: 'ranged',
    subType: 'longbow',
    rarity: 'unique',
    power: 30,
    icon: '🐍',
    color: '#dc2626',
    damage: 68,
    range: 30,
    attackSpeed: 0.7,
    arrowCost: 1,
    description: 'A master sniper longbow with chance to shoot piercing explosive arrows.',
    uniquePerk: 'Strong charged sniper arrows',
    enchantmentSlots: [
      { id: 'power', tier: 1 },
      { id: 'infinity', tier: 0 },
    ],
    salvageEmeralds: 140,
  },
  {
    id: 'hunters_bow',
    name: "Hunter's Bow",
    category: 'ranged',
    subType: 'bow',
    rarity: 'common',
    power: 15,
    icon: '🎯',
    color: '#ca8a04',
    damage: 28,
    range: 22,
    attackSpeed: 1.0,
    arrowCost: 1,
    description: 'A standard curved wooden bow used for hunting and ranged skirmishing.',
    enchantmentSlots: [
      { id: 'power', tier: 0 },
      { id: 'infinity', tier: 0 },
    ],
    salvageEmeralds: 30,
  },
];

// --- ARMOR CATALOG ---
export const ALL_ARMOR: DungeonsGearItem[] = [
  {
    id: 'starter_leather_tunic',
    name: 'Worn Leather Tunic',
    category: 'armor',
    subType: 'light',
    rarity: 'common',
    power: 1,
    icon: '🥋',
    color: '#854d0e',
    hpBonus: 20,
    damageReduction: 0.05,
    description: 'A modest stitched leather tunic offering entry-level defense for wandering explorers.',
    enchantmentSlots: [
      { id: 'protection', tier: 0 },
    ],
    salvageEmeralds: 5,
  },
  {
    id: 'mercenary_armor',
    name: 'Mercenary Armor',
    category: 'armor',
    subType: 'medium',
    rarity: 'unique',
    power: 34,
    icon: '🛡️',
    color: '#f59e0b',
    hpBonus: 65,
    damageReduction: 0.25,
    description: 'Rugged combat armor worn by hardened Overworld sellswords.',
    uniquePerk: '+25% Melee damage, +65 Max HP, -25% Damage taken',
    enchantmentSlots: [
      { id: 'protection', tier: 1 },
      { id: 'thorns', tier: 1 },
      { id: 'potion_barrier', tier: 0 },
    ],
    salvageEmeralds: 160,
  },
  {
    id: 'evocation_robe',
    name: 'Evocation Robe',
    category: 'armor',
    subType: 'robe',
    rarity: 'unique',
    power: 36,
    icon: '🧙‍♂️',
    color: '#a855f7',
    hpBonus: 40,
    damageReduction: 0.1,
    soulGathering: 2,
    moveSpeedBonus: 0.15,
    description: 'Flowing enchanted vestments favored by battle sorcerers.',
    uniquePerk: '-40% Artifact cooldown, +15% Speed, +2 Soul gathering',
    enchantmentSlots: [
      { id: 'swiftfooted', tier: 1 },
      { id: 'protection', tier: 0 },
      { id: 'potion_barrier', tier: 0 },
    ],
    salvageEmeralds: 175,
  },
  {
    id: 'titans_shroud',
    name: "Titan's Shroud",
    category: 'armor',
    subType: 'heavy',
    rarity: 'unique',
    power: 38,
    icon: '🦺',
    color: '#0284c7',
    hpBonus: 95,
    damageReduction: 0.35,
    description: 'Impenetrable plate forged to withstand catastrophic blows from Redstone Golems.',
    uniquePerk: 'Massive +95 HP and +35% Damage reduction',
    enchantmentSlots: [
      { id: 'protection', tier: 2 },
      { id: 'thorns', tier: 1 },
      { id: 'potion_barrier', tier: 1 },
    ],
    salvageEmeralds: 190,
  },
  {
    id: 'champion_armor',
    name: "Champion's Armor",
    category: 'armor',
    subType: 'heavy',
    rarity: 'unique',
    power: 40,
    icon: '👑',
    color: '#38bdf8',
    hpBonus: 110,
    damageReduction: 0.38,
    moveSpeedBonus: 0.05,
    description: 'Masterwork diamond-inlaid armor forged for legendary conquerors of the realm.',
    uniquePerk: '+38% Damage reduction, +110 Max HP, radiant defiance aura',
    enchantmentSlots: [
      { id: 'protection', tier: 2 },
      { id: 'thorns', tier: 2 },
      { id: 'potion_barrier', tier: 1 },
    ],
    salvageEmeralds: 220,
  },
  {
    id: 'golden_knight_armor',
    name: 'Golden Knight Carapace',
    category: 'armor',
    subType: 'heavy',
    rarity: 'unique',
    power: 37,
    icon: '✨',
    color: '#eab308',
    hpBonus: 85,
    damageReduction: 0.3,
    description: 'Dazzling gilded armor that converts absorbed damage into emerald drops and shields.',
    uniquePerk: '+30% Damage reduction, bonus emerald generation in combat',
    enchantmentSlots: [
      { id: 'protection', tier: 1 },
      { id: 'potion_barrier', tier: 1 },
    ],
    salvageEmeralds: 195,
  },
  {
    id: 'grim_armor',
    name: 'Grim Armor',
    category: 'armor',
    subType: 'medium',
    rarity: 'rare',
    power: 28,
    icon: '💀',
    color: '#64748b',
    hpBonus: 50,
    damageReduction: 0.2,
    soulGathering: 3,
    description: 'Forged from dark souls of the Nether chasm, granting life steal on melee strikes.',
    uniquePerk: '+3 Soul gathering and +3% life steal on kill',
    enchantmentSlots: [
      { id: 'protection', tier: 1 },
      { id: 'swiftfooted', tier: 0 },
    ],
    salvageEmeralds: 110,
  },
  {
    id: 'hunter_tunic',
    name: "Ranger's Hunter Tunic",
    category: 'armor',
    subType: 'light',
    rarity: 'common',
    power: 16,
    icon: '🏹',
    color: '#16a34a',
    hpBonus: 25,
    damageReduction: 0.1,
    moveSpeedBonus: 0.12,
    description: 'Lightweight forest garment with leather bracers for agile exploration.',
    enchantmentSlots: [
      { id: 'swiftfooted', tier: 0 },
    ],
    salvageEmeralds: 35,
  },
  {
    id: 'iron_plate',
    name: 'Iron Breastplate',
    category: 'armor',
    subType: 'medium',
    rarity: 'common',
    power: 18,
    icon: '🛡️',
    color: '#cbd5e1',
    hpBonus: 35,
    damageReduction: 0.18,
    description: 'Sturdy hammered iron plate capable of stopping heavy blows.',
    enchantmentSlots: [
      { id: 'protection', tier: 0 },
    ],
    salvageEmeralds: 40,
  },
  {
    id: 'wolf_armor',
    name: 'Wolf Armor',
    category: 'armor',
    subType: 'light',
    rarity: 'rare',
    power: 24,
    icon: '🐺',
    color: '#94a3b8',
    hpBonus: 35,
    damageReduction: 0.15,
    moveSpeedBonus: 0.1,
    description: 'Cured leather armor that increases speed and bolsters companion damage.',
    uniquePerk: '+10% Movement speed and healing aura on potion',
    enchantmentSlots: [
      { id: 'swiftfooted', tier: 0 },
      { id: 'protection', tier: 0 },
    ],
    salvageEmeralds: 65,
  },
];

// --- MISSIONS CATALOG ---
export const DUNGEONS_MISSIONS: DungeonsMission[] = [
  {
    id: 'squid_coast',
    name: 'Squid Coast',
    icon: '🦑',
    region: 'Coastal Village',
    description: 'Learn the fundamentals of combat and survive your first wave of illager raiders.',
    recommendedPower: 1,
    difficulty: 'Default',
    targetKills: 8,
    targetChests: 1,
    potentialDrops: ["Hunter's Bow", 'Iron Broadsword', 'Boots of Swiftness'],
  },
  {
    id: 'creeper_woods',
    name: 'Creeper Woods',
    icon: '🌲',
    region: 'Overworld Forest',
    description: 'Venture through dark spruce woods teeming with Creepers, Skeletons, and trapped villagers.',
    recommendedPower: 8,
    difficulty: 'Default',
    targetKills: 16,
    targetChests: 2,
    potentialDrops: ['Diamond Sword', 'Tasty Bone', 'Death Cap Mushroom'],
  },
  {
    id: 'pumpkin_pastures',
    name: 'Pumpkin Pastures',
    icon: '🎃',
    region: 'Farmlands',
    description: 'Battle through ruined autumn homesteads and burn down the Illager siege barricades.',
    recommendedPower: 16,
    difficulty: 'Default',
    targetKills: 24,
    targetChests: 3,
    potentialDrops: ['Mercenary Armor', 'Wind Horn', 'Firebolt Bow'],
  },
  {
    id: 'soggy_swamp',
    name: 'Soggy Swamp',
    icon: '🐸',
    region: 'Murky Marsh',
    description: 'Sludge through deep mossy waters, defeat vile witches, and overcome the Corrupted Cauldron!',
    recommendedPower: 22,
    difficulty: 'Adventure',
    targetKills: 30,
    targetChests: 3,
    potentialDrops: ['Cursed Axe', 'Harvester', 'Harp Crossbow'],
    bossName: 'Corrupted Cauldron',
  },
  {
    id: 'redstone_mines',
    name: 'Redstone Mines',
    icon: '⛏️',
    region: 'Underground Chasm',
    description: 'Infiltrate the glowing redstone shafts where the Arch-Illager manufactures monstrous weapons.',
    recommendedPower: 28,
    difficulty: 'Adventure',
    targetKills: 35,
    targetChests: 4,
    potentialDrops: ["Fighter's Bindings", 'Corrupted Beacon', "Titan's Shroud"],
    bossName: 'Redstone Golem',
  },
  {
    id: 'obsidian_pinnacle',
    name: 'Obsidian Pinnacle',
    icon: '🏰',
    region: 'Imperial Citadel',
    description: 'Scale the majestic mountain fortress and confront the Arch-Illager and the Heart of Ender!',
    recommendedPower: 35,
    difficulty: 'Apocalypse',
    targetKills: 45,
    targetChests: 5,
    potentialDrops: ["Sun's Grace", 'Red Snake', 'Evocation Robe'],
    bossName: 'Arch-Illager & Heart of Ender',
  },
];

// Initial default gear setup for a new character in Minecraft Dungeons style
export const INITIAL_MELEE: DungeonsGearItem = ALL_MELEE_WEAPONS.find(w => w.id === 'starter_wooden_sword') || ALL_MELEE_WEAPONS[0];
export const INITIAL_RANGED: DungeonsGearItem = ALL_RANGED_WEAPONS.find(w => w.id === 'starter_shortbow') || ALL_RANGED_WEAPONS[0];
export const INITIAL_ARMOR: DungeonsGearItem = ALL_ARMOR.find(a => a.id === 'starter_leather_tunic') || ALL_ARMOR[0];
export const INITIAL_ARTIFACTS: [DungeonsArtifact | null, DungeonsArtifact | null, DungeonsArtifact | null] = [
  null,
  null,
  null,
];

// Procedural gear drop generator matching player power level
export function getRandomDrop(powerLevel: number): DungeonsGearItem | DungeonsArtifact {
  const pool = [...ALL_MELEE_WEAPONS, ...ALL_RANGED_WEAPONS, ...ALL_ARMOR, ...ALL_ARTIFACTS];
  const template = pool[Math.floor(Math.random() * pool.length)];
  const itemPower = Math.max(1, (powerLevel || 1) + Math.floor(Math.random() * 5) - 2);
  return {
    ...template,
    id: `${template.id}_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    power: itemPower,
  };
}
